<?php $this->template('pages/header.tpl')?>
<div class="foot">
<div class="l-main-container" style="background:url(../images/hears.png) no-repeat 50% 29px;">
	<div class="l-wrapper-up">
	<div class="l-wrapper">
		<div class="l-header" style="background:url(../images/hears.png) no-repeat 50% 29px;">
			<div class="l-header-i new-bg">
                                <?php $this->template('pages/topmenu.tpl')?>
                               <!-- <div class="b-head-img b-head-img-inner clrfix">
					<img src="<?=Config::get('path/host');?>images/title-catalog.png" width="302" height="22" align="" class="fr" />
				</div>-->
			</div>
		</div>
		<div class="l-container" style="width: 880px">
            <p style="text-align: center;">
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: center; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;"><strong>УСЛОВИЯ ПОЛЬЗОВАНИЯ САЙТОМ WWW.GOPHOTOWEB.RU</strong></span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">Добро пожаловать на сайт Gophotoweb, расположенный по адресу <a href="http://www.gophotoweb.ru">http://www.gophotoweb.ru</a> и предоставляющий услуги по созданию стильных и современных сайтов для тех,&nbsp; кто может презентовать свою работу с помощью фотографий и видео-роликов.&nbsp;</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">Спасибо за посещение.&nbsp;</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">Для нас важно, чтобы Вам и другим посетителям нашего Сайта было удобно пользоваться им, и чтобы в процессе пользования Сайтом вы были осведомлены о возникающих в этой связи юридических правах и обязанностях. С этой целью мы составили настоящие Условия, представляющие собой юридически обязательные правила пользования настоящим Сайтом. Внимательно ознакомьтесь с ними, прежде чем начать пользоваться предоставленным ресурсом, так как эти Условия&nbsp; регламентируют&nbsp; Ваши юридические права и обязанности.</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;"><strong>Принятие условий.&nbsp;</strong></span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">Не пользуйтесь Сайтом, если Вы не согласны с какими-либо из настоящих Условий. Факт посещения этого Сайта и (или) любой из его страниц считается подтверждением ознакомления посетителя с изложенными ниже основными правилами,&nbsp; правовой информацией о настоящем Сайте и размещенных на нем материалах и подразумевает Ваше безотзывное и полное согласие с настоящими условиями.</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">В отношении некоторых разделов настоящего&nbsp; Сайта могут действовать дополнительные условия и положения, с которыми Вы должны внимательно ознакомиться, прежде чем воспользоваться этими&nbsp; разделами. Такие дополнительные условия не изменяют и не заменяют собой настоящие Условия пользования данным Сайтом, если иное не будет прямо оговорено.&nbsp;</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">Обращаем Ваше внимание, что настоящие Условия пользования могут пересматриваться или переиздаваться в любое время без дополнительного уведомления путем обновления данного сообщения. В целях ознакомления с внесенными изменениями, а также действующими Условиями пользования Сайта Вы должны регулярно посещать данную страницу. Дальнейшее использование Вами Сайта, после внесения изменений в Условия пользования,&nbsp; предполагает безотзывное принятие Вами любых изменений и полное согласие с ними.</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;"><strong>Информация о предоставляемой услуге</strong></span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">Индивидуальный предприниматель Суслова Ю.В., как &nbsp; Исполнитель обязуется выполнить работы по созданию для Заказчика веб-сайта и системы управления веб-сайтом в соответствии с шаблонами, представленными Исполнителем в каталоге, а также разместить веб-сайт в сети Интернет (установить и настроить сайт&nbsp; на хостинге Заказчика) и оказывать услуги по технической поддержке веб-сайта.&nbsp;</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;"><strong>Исключительные права на Шаблоны и Контент, размещенный на Сайте.&nbsp;</strong></span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">Все объекты, размещенные на Сайте, в том числе шаблоны сайтов, элементы дизайна, текст, графические изображения, иллюстрации, видео, скрипты, программы, музыка, звуки и другие объекты и их подборки (далее &mdash; Контент), являются объектами исключительных прав ИП Сусловой Ю.В. и других правообладателей, все права на эти объекты защищены.&nbsp;</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">Кроме случаев, установленных настоящими Правилами, а также действующим законодательством Российской Федерации, никакой Контент, в том числе и система управления сайтом от GoPhotoWeb (далее по тексту - Программное обеспечение) не может быть скопирован (воспроизведен), переработан, распространен, отображен во фрейме, опубликован, скачан, передан, продан или иным способом использован целиком или по частям без предварительного разрешения правообладателя, кроме случаев, когда правообладатель явным образом выразил свое согласие на свободное использование Контента или системы управления сайтом GoPhotoWeb любым лицом.&nbsp;</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;"><strong>Лицензионное соглашение пользователя Программного обеспечения по управлению сайтом GoPhotoWeb</strong></span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">Пожалуйста, внимательно ознакомьтесь с настоящим Соглашением перед тем, как воспользоваться услугами, предлагаемыми ИП СУСЛОВОЙ Ю.В. и сайтом&nbsp; www.gophotoweb.ru</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">Использование готовых сайтов и системы управления сайтом от GoPhotoWeb (именуемое далее, как &laquo;Программное обеспечение&raquo;), включая любые изменения, усовершенствования, обновления&nbsp; подлежит согласованию с ИП Сусловой Ю.В. и (или) администрацией сайта<span style="font: 11.0px Calibri; letter-spacing: 0.0px;"> </span><span style="letter-spacing: 0.0px;">Gophotoweb и подпадает под действие настоящих&nbsp; Условий лицензионного соглашения.&nbsp;</span></span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">Получая сайт и Программное обеспечение по управлению сайтом, в том числе и тестовом режиме,&nbsp; Вы подтверждаете, что с Условиями лицензионного соглашения , а также с Положением о конфиденциальности информации вы ознакомлены и полностью с ними согласны. Если вы не согласны с настоящим лицензионным соглашением&nbsp; и&nbsp; Положением о конфиденциальности , и (или) не желаете быть СВЯЗАННЫМИ условиями указанных документов,&nbsp; не отправляйте форму заказа сайта, а в случае получения такого доступа ранее не используйте&nbsp; его как по прямому назначению, так и в иных целях.&nbsp;</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0px;">ИП Суслова Ю.В. и Администрация сайта&nbsp; Gophotoweb&nbsp; предоставляют вам, а вы принимаете в личное&nbsp; пользование эксклюзивное, не подлежащее передаче и сублицензированию, Программное обеспечение, которое включает в себ сайт и систему управления сайтом, специально разработанное для&nbsp; фотографов.&nbsp;</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">Все права на Программное обеспечение, разработанное GoPhotoWeb , в том числе и&nbsp; специально не оговоренные в настоящем соглашении, как&nbsp; переданные или предоставленные пользователю, остаются принадлежащими ИП Сусловой Ю.В. и Администрации сайта Gophotoweb, даже после получения Пользователем правомерного&nbsp; доступа к настоящему Программному обеспечению.</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;"><strong>Запрещенное использование.</strong></span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">Получая доступ, в том числе и в тестовом режиме, к Программному обеспечению, вы соглашаетесь с тем, что без предварительного письменного согласия ИП Сусловой Ю.В.&nbsp; и (или) Администрации сайта Gophotoweb (за исключением специально разрешенных настоящими условиями)&nbsp; вы ОБЯЗУЕТЕСЬ:</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">1). Использовать Программное обеспечение по его прямому назначению,&nbsp; не&nbsp; изменять и&nbsp; не комбинировать с другим программным обеспечением, не нарушать и не изменять исходного кода полученного при создании сайта шаблона, если такие изменения повлекут за собой невосполнимую утрату функционала системы управления сайта.</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">2). Не копировать, не распространять&nbsp; и (или)&nbsp; не&nbsp; воспроизводить Контент, размещенный на сайте</span><span style="font: 11.0px Calibri; letter-spacing: 0.0px;"> </span><span style="letter-spacing: 0.0px;">GoPhotoWeb&nbsp; (<a href="http://gophotoweb.ru/"><span style="text-decoration: underline; letter-spacing: 0.0px; color: #3600fe;">http://gophotoweb.ru/</span></a>), а также Программное обеспечение&nbsp; с целью их передачи третьим лицам.&nbsp;</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">3). Не раскрывать&nbsp; третьим лицам результаты изучения технических возможностей Программного обеспечения, и не&nbsp; использовать эти результаты для создания собственного&nbsp; конкурирующего с ИП Сусловой Ю.В. и сайтом&nbsp; Gophotoweb вида&nbsp; деятельности в области создания сайтов,&nbsp; продвижения&nbsp; и реализации аналогичного программного обеспечения.</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;"><strong>Техническое обслуживание и поддержка.</strong></span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">ИП Суслова Ю.В. и Администрация сайта Gophotoweb заверяют, что&nbsp; будут проводить&nbsp; техническое обслуживание и осуществлять поддержку сайтов Пользователей, созданных с использованием системы управления&nbsp; сайтом&nbsp; GoPhotoWeb&nbsp; и зарегистрированных на хостинге GoPhotoWeb.</span></p>
			<p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;"><strong>Отказ от гарантий.</strong></span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">Программное обеспечение предоставляется &laquo;как есть&raquo;,&nbsp; без каких-либо гарантий любого вида. ИП Суслова Ю.В. и Администрация сайта&nbsp; Gophotoweb не гарантируют, что Программное обеспечение будет отвечать требованиям Пользователей,&nbsp; или что функционирование&nbsp; Системы управления сайтом&nbsp; будет непрерывно, или без ошибок.&nbsp;</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">Вы признаете, что любые данные или информация, загруженные&nbsp; на ваш сайт,созданный с использованием системы управления GoPhotoWeb&nbsp; , в период вашего непосредственного пользования этой системой (администрирование, модерирование и т.п.) являются&nbsp; одними из ваших рисков и ИП Суслова Ю.В. и Администрация сайта&nbsp; Gophotoweb не будут нести ответственность за результаты указанных действий, а также за любой ущерб, причиненный вам или вашей собственности (например, в результате хищения контента созданного вами сайта, плагиата)</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;"><strong>Прекращение</strong></span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">ИП Суслова В.П.&nbsp; может в любое время и по любой причине&nbsp; прекратить действие предоставляемой здесь лицензии.&nbsp;</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">Ваш отказ выполнять условия настоящего Соглашения также незамедлительно прекращает&nbsp; вашу лицензию на использование&nbsp; Системы управления сайтом GoPhotoWeb.&nbsp; После расторжения настоящего соглашения ИП Суслова Ю.В. и (или) Администрация сайта</span><span style="font: 11.0px Calibri; letter-spacing: 0.0px;"> </span><span style="letter-spacing: 0.0px;">Gophotoweb :</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">1). Аннулируют настоящую лицензию, предоставленную вам в этом соглашении, и вы&nbsp; должны незамедлительно самостоятельно прекратить дальнейшее использование Программного обеспечения.</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">2). Блокируют на определенный срок созданный Пользователем с использованием системы управления GoPhotoWeb сайт, о чем Пользователю направляется письменное&nbsp; уведомление по реквизита, указанным им при заполнении специальной формы регистрации на сайте Gophotoweb.</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">3). В случае если в указанный в уведомлении срок Пользователь не изменит своего отношения и не устранит допущенные им нарушения, ИП Суслова Ю.В. и Администрация сайта Gophotoweb, имеют право удалить ранее блокированный сайт Пользователя, однако сохранить копию удаленного сайта и хранить ее 12 месяцев, с тем, чтобы Пользователь&nbsp; в любое время в указанный период имел реальную возможность восстановить созданный им ранее сайт.</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;"><strong>Заключительные положения</strong></span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">Условия настоящего соглашения&nbsp; должны толковаться и регулироваться&nbsp; в соответствии с законами Российской Федерации (за исключением конфликта правовых норм). Все споры&nbsp; по данному соглашению или&nbsp; вытекающие из него подлежат разрешению в суде по месту нахождения ответчика или, по соглашению сторон, по месту регистрации ИП Сусловой Ю.В..</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">Если какая-либо часть данных Условий пользования будет признана недействительной или невыполнимой в связи с применимым законом, включая без ограничения вышеприведенные оговорки по гарантиям и ограничению ответственности, тогда недействительное или неприменимое положение считаются замененными действительным, выполнимым положением, наиболее близко соответствующим намерению первоначального положения, при этом остальная часть Условий пользования остается в силе.</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">Настоящие Условия составлены в соответствии с Гражданским кодексом Российской Федерации&nbsp; и представляют собой документ, регулирующий отношения между сторонами по&nbsp; изложенным в нем вопросам.</span></p>
            <p style="margin: 0.0px 0.0px 10.0px 0.0px; text-align: justify; font: 11.0px Verdana;"><span style="letter-spacing: 0.0px;">Печатные версии скриншотов страниц Сайта и настоящих&nbsp; Условий, а также любого уведомления в электронной форме, связанного с работой системы управления сайтом, при надлежащем их заверении могут быть приняты в качестве доказательств по спорным вопросам&nbsp; в судебном и административном производстве.</span></p>
            </p>
		</div>
	</div>
</div>
</div>
<?php $this->template('pages/footer.tpl');?>
</div>
</div>
<?php $this->template('pages/popup.tpl');?>

</body>
</html>

